export const person = [
  {
    id: 0,
    name: "Alex Turner",
    sequence: [square3, square6, square10, square16, square7, square3],
    image: "alex.png",
  },
  {
    id: 1,
    name: "Alex Turner",
    sequence: [square3, square6, square10, square16, square7, square3],
    image: "alex.png",
  },
  {
    id: 2,
    name: "Miley Cyrus",
    sequence: [square7, square6, square23, square14, square15, square6],
    image: "Miley.png",
  },
  {
    id: 3,
    name: "Tom Jones",
    sequence: [square7, square3, square11, square15, square21, square3],
    image: "Tom.png",
  },
  {
    id: 4,
    name: "Art Garfunkel",
    sequence: [square6, square3, square15, square7, square15, square3],
    image: "art.png",
  },
  {
    id: 5,
    name: "Charles Bronson",
    sequence: [square11, square12, square17, square10, square15, square3],
    image: "bronson.png",
  },
  {
    id: 6,
    name: "Fred Durst",
    sequence: [square12, square16, square10, square15, square7, square3],
    image: "fred.png",
  },
  {
    id: 7,
    name: "Jon Snow",
    sequence: [square7, square2, square23, square14, square15, square6],
    image: "jon.png",
  },
  {
    id: 8,
    name: "Craig David",
    sequence: [square2, square3, square14, square6, square15, square3],
    image: "craig.png",
  },
  {
    id: 9,
    name: "James Corden",
    sequence: [square6, square8, square14, square10, square7, square3],
    image: "james.png",
  },
  {
    id: 10,
    name: "Pablo Escobar",
    sequence: [square2, square6, square10, square11, square15, square3],
    image: "pablo.png",
  },
  {
    id: 11,
    name: "Ray Charles",
    sequence: [square3, square6, square10, square16, square7, square3],
    image: "ray.png",
  },
  {
    id: 12,
    name: "Tim Key",
    sequence: [square6, square7, square8, square9, square2, square5],
    image: "tim.png",
  },
  {
    id: 13,
    name: "Terry Pratchett",
    sequence: [square14, square17, square10, square8, square15, square3],
    image: "Terry.png",
  },
  {
    id: 14,
    name: "Bob Ross",
    sequence: [square17, square2, square14, square10, square15, square3],
    image: "Bo.png",
  },
  {
    id: 15,
    name: "Ryan Reynolds",
    sequence: [square6, square16, square2, square9, square15, square3],
    image: "Ryan.png",
  },
  {
    id: 16,
    name: "Julius Caesar",
    sequence: [square8, square22, square10, square16, square7, square3],
    image: "ceasar.png",
  },
  {
    id: 17,
    name: "Vincent Van Gogh",
    sequence: [square7, square2, square23, square14, square15, square6],
    image: "vincent.png",
  },
  {
    id: 18,
    name: "Pablo Picasso",
    sequence: [square7, square3, square14, square6, square15, square3],
    image: "Picasso.png",
  },
  {
    id: 19,
    name: "Neil Buchanan",
    sequence: [square1, square23, square14, square10, square15, square3],
    image: "Buchanan.png",
  },
  {
    id: 20,
    name: "Michelangelo",
    sequence: [square6, square24, square11, square10, square15, square3],
    image: "Michelangelo.png",
  },
  {
    id: 21,
    name: "Justin Trudeau",
    sequence: [square6, square4, square11, square10, square15, square3],
    image: "Justin.png",
  },
  {
    id: 22,
    name: "Jurgen Klopp",
    sequence: [square10, square2, square11, square17, square15, square3],
    image: "Klopp.png",
  },
  {
    id: 23,
    name: "Steve Jobs",
    sequence: [square23, square17, square16, square11, square15, square3],
    image: "jobs.png",
  },
  {
    id: 24,
    name: "Billie Eilish",
    sequence: [square22, square5, square11, square10, square15, square3],
    image: "Billie.png",
  },
  {
    id: 25,
    name: "Gene Simmons",
    sequence: [square18, square19, square16, square6, square10, square3],
    image: "gene.png",
  },
  {
    id: 26,
    name: "Robert Smith",
    sequence: [square6, square24, square11, square10, square15, square3],
    image: "smith.png",
  },
  {
    id: 27,
    name: "Pierce Brosnan",
    sequence: [square10, square19, square6, square16, square15, square3],
    image: "Pierce.png",
  },
  {
    id: 28,
    name: "Mark Zuckerberg",
    sequence: [square18, square10, square2, square4, square11, square3],
    image: "Mark.png",
  },
  {
    id: 29,
    name: "Tina Fey",
    sequence: [square6, square24, square11, square10, square15, square3],
    image: "tina.png",
  },
  {
    id: 30,
    name: "Hulk Hogan",
    sequence: [square11, square12, square15, square16, square10, square3],
    image: "Hulk.png",
  },
  {
    id: 31,
    name: "Gary Lineker",
    sequence: [square7, square10, square2, square11, square21, square4],
    image: "Gary.png",
  },
];
